### ISSUE TITLE
FreeBSD 8.3 Authy-SSH Install

### ISSUE THREAD

**Issue by rogueops** [authy/authy-ssh#34]
Cannot get it to prompt for code after install. Got it to install just fine and enable a user. When logging in via SSH i get to the password and after entering a password the window just closes.

authy-ssh test:

/usr/local/bin/authy-ssh: line 554: seq: command not found

FreeBSD 8.3 - PFSense

I got google-auth to work just fine.

Got it to work after modifying the install script

**Comment by gh0stshell** [comment]
I already resolved it on my own by modifying the script.

**Comment by gh0stshell** [comment]
I will test your new script to see if it works on the latest release.

**Comment by gh0stshell** [comment]
found a few more things in the version 1.7 script
